---
homebrew_taps:
  - { tap: homebrew/cask-versions }
  - { tap: homebrew/cask-fonts }
  - { tap: sanemat/font }
  - { tap: kevwil/patches }
  - { tap: bfontaine/utils }
  - { tap: caarlos0/antibody }
  - { tap: caius/jo }

homebrew_cask_packages:
  - { name: iterm2 }
  - { name: google-chrome }
  - { name: google-japanese-ime }
  - { name: java }
  - { name: xquartz }
  - { name: alfred }
#  - { name: caffeine}
  - { name: clipy}
  - { name: thunderbird}
  - { name: dropbox}
  - { name: appcleaner}
  - { name: imageoptim}
  - { name: musescore}
  - { name: visual-studio-code}
  - { name: duet}
  - { name: basictex}
  - { name: adobe-creative-cloud}
  - { name: font-ricty-diminished}
#  - { name: microsoft-office}
#  - { name: firefox}
  - { name: vox}
  - { name: skim}
  - { name: pycharm }

homebrew_packages:
  - { name: cask }
  - { name: libxml2 }
  - { name: glib }
  - { name: fontconfig }
  - { name: readline }
  - { name: openssl }
  - { name: python }
  - { name: python3 }
  - { name: pyenv }
  - { name: coreutils }
  - { name: git }
  - { name: wget }
  - { name: curl }
  - { name: cmake }
  - { name: autoconf }
  - { name: automake }
  - { name: pkg-config }
  - { name: ctags }
  - { name: tree }
  - { name: nkf }
  - { name: sha2 }
#  - { name: bash }
#  - { name: zsh }
  - { name: freetype }
  - { name: argon/mas/mas }
  - { name: ffmpeg }
  - { name: vim, install_options: --with-lua }

add_permission_directories:
  - { name: /usr/local/bin }
  - { name: /usr/local/etc }
  - { name: /usr/local/include }
  - { name: /usr/local/lib }
  - { name: /usr/local/sbin }
  - { name: /usr/local/share }
  - { name: /usr/local/var }
  - { name: /usr/local/Frameworks }
  - { name: /usr/local/var/homebrew }


