---
- name: Check if iterm2 config is differ
  shell: |
    diff <(plutil -convert binary1 -o - ./com.googlecode.iterm2.plist | md5 -q) <(md5 -q ~/Library/Preferences/com.googlecode.iterm2.plist)
  args:
    chdir: ../settingfile
    executable: /bin/bash
  register: diff_result
  failed_when: false
  changed_when: diff_result.rc != 0
  notify:
    - Restore iterm2 configuration

# 奥深くにあるコマンドのリンクを作りどこでも使えるようにする
- name: Create alias symlink
  file:
    src: "{{ item.src }}"
    dest: "/usr/local/bin/{{ item.dest }}"
    state: link
  with_items:
    - "{{ symlinks }}"

- name: Setup OS X defaults
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  notify:
    - "{{ item.notify | default(omit) }}"
  with_items:
    - "{{ osx_defaults }}"
