---
symlinks:
  - { src: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport, dest: airport }  # WiFiのステータス表示
  - { src: "/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py", dest: join.py }  # PDF結合

osx_defaults:
  # Dockを自動的に隠す
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    notify: "Restart Dock"

  # Dockをすぐに表示する
  - domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    notify: "Restart Dock"

  # 拡張子を常に表示
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    notify: "Restart Finder"

  # 隠しファイルを表示
  # - domain: com.apple.finder
  #   key: AppleShowAllFiles
  #   type: bool
  #   value: true
  #   notify: "Restart Finder"

  # FinderにPathBarを表示
  - domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    notify: "Restart Finder"

  # Networkドライブ（NASなど）に.DS_Storeを作らない
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    notify: "Restart Finder"

  # リピートキー入力速度向上
  # - domain: NSGlobalDomain
  #   key: InitialKeyRepeat
  #   type: int
  #   value: 15
  # - domain: NSGlobalDomain
  #   key: KeyRepeat
  #   type: int
  #   value: 2
