---
ghq_root: "{{ user_dir }}/dotfiles/repo"

# git_repositories:
#   - { repo: "https://github.com/edihbrandon/RictyDiminished.git", dest: "{{ ghq_root }}/edihbrandon/RictyDiminished" }

symlinks:
  - { src: "{{ ansible_dir }}/../settingfile/vimrc", dest: "{{ user_dir }}/.vimrc" }
  - { src: "{{ ansible_dir }}/../settingfile/dein.toml", dest: "{{ user_dir }}/.dein.toml" }
