#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# remove brew warning when use pyenv
alias brew="env PATH=${PATH/\/Users\/naoya\/\.pyenv\/shims:/} brew"
export HOMEBREW_GITHUB_API_TOKEN=eef8e7e0e04ad498ceb6eeabe747183dc2730b01
export PATH=$HOME/.nodebrew/current/bin:$PATH

alias vim='nvim'

if [ -e "/opt/ros/dashing/setup.zsh" ]; then
    source /opt/ros/dashing/setup.zsh
fi
